const audio=t=>`<button class="sound" onclick="event.stopPropagation();speak('${t.replace(/'/g,"\\'")}')">🔊 發音</button>`;
const vocab=[
{ko:'회사',zh:'公司',pos:'名詞',note:'指公司、企業或工作的組織。常與 에（去某處）、에서（在某處做事）一起使用。',ex:'회사에 가요.',exZh:'去公司。',parts:[['회사','公司'],['에','方向／目的地助詞，表示「去公司」'],['가요','가다（去）＋아요／어요 禮貌語尾']],grammar:'名詞＋에＋移動動詞。에 放在地點後，表示移動的目的地；가요 是 가다 的日常禮貌說法。'},
{ko:'회의',zh:'會議',pos:'名詞',note:'指工作上的會議、討論會。常用 회의가 있다（有會議）、회의를 하다（開會）。',ex:'회의가 있어요.',exZh:'有會議。',parts:[['회의','會議'],['가','主格助詞，標示「會議」是句子的主體'],['있어요','있다（有、存在）＋어요 禮貌語尾']],grammar:'名詞＋이／가＋있어요，表示「有某物／某事」。회의 最後是母音，所以使用 가。'},
{ko:'자료',zh:'資料',pos:'名詞',note:'指文件、數據、簡報或工作所需的參考內容。',ex:'자료를 봐요.',exZh:'看資料。',parts:[['자료','資料'],['를','受詞助詞，表示資料是「看」的對象'],['봐요','보다（看）→ 봐요，日常禮貌形']],grammar:'名詞＋을／를＋動詞。자료 最後是母音，因此使用 를；보다 與 아요 結合後縮寫成 봐요。'},
{ko:'준비하다',zh:'準備',pos:'動詞',note:'表示為某件事情事先整理、安排或備妥。하다 類動詞會變化為 해요。',ex:'회의를 준비해요.',exZh:'準備會議。',parts:[['회의','會議'],['를','受詞助詞'],['준비해요','준비하다（準備）→ 준비해요']],grammar:'名詞＋을／를＋하다 類動詞。하다 在 아요／어요 禮貌形中通常變成 해요，所以 준비하다 → 준비해요。'},
{ko:'확인하다',zh:'確認',pos:'動詞',note:'指查看後確認內容、狀態或安排，是職場中非常常用的動詞。',ex:'자료를 확인해요.',exZh:'確認資料。',parts:[['자료','資料'],['를','受詞助詞'],['확인해요','확인하다（確認）→ 확인해요']],grammar:'名詞＋을／를＋확인하다。하다 變成 해요；若要更正式地回報已完成，可說 확인했습니다（已確認）。'},
{ko:'보내다',zh:'傳送／寄送',pos:'動詞',note:'可用於傳訊息、寄文件、寄電子郵件，也可表示送某人離開。',ex:'메시지를 보내요.',exZh:'傳送訊息。',parts:[['메시지','訊息'],['를','受詞助詞'],['보내요','보내다（傳送、寄送）＋어요']],grammar:'名詞＋을／를＋보내요。보내다 的語幹是 보내-，接 어요 後成為 보내요。'},
{ko:'오늘',zh:'今天',pos:'時間名詞／副詞',note:'表示今天。作為時間詞時通常不需要加助詞，也可以說 오늘은（至於今天）。',ex:'오늘 만나요.',exZh:'今天見面。',parts:[['오늘','今天'],['만나요','만나다（見面）→ 만나요']],grammar:'時間詞＋動詞。오늘 可直接放在句首；만나다 接 아요 後形成 만나요。'},
{ko:'내일',zh:'明天',pos:'時間名詞／副詞',note:'表示明天。正式職場訊息中常搭配 뵙겠습니다，向上級表示「明天見」。',ex:'내일 뵙겠습니다.',exZh:'明天見。',parts:[['내일','明天'],['뵙겠습니다','뵙다（見面的謙讓語）＋겠습니다（正式意志／預定）']],grammar:'時間詞＋謙讓動詞＋겠습니다。뵙다 用於見上級或長輩，-겠습니다 使語氣正式而有禮貌。'},
{ko:'먼저',zh:'先、首先',pos:'副詞',note:'表示在其他人或其他事情之前先做某事。',ex:'먼저 가세요.',exZh:'請先走。',parts:[['먼저','先'],['가세요','가다（去）＋세요（尊敬／禮貌請求）']],grammar:'副詞＋動詞。-세요 可用來禮貌地請對方做某事；가다 加 세요 後為 가세요。'},
{ko:'감사합니다',zh:'謝謝',pos:'正式敬語表達',note:'由 감사하다（感謝）變化而來，是正式且常用的道謝方式。',ex:'정말 감사합니다.',exZh:'真的謝謝您。',parts:[['정말','真的、非常'],['감사합니다','감사하다（感謝）＋ㅂ니다 正式敬語語尾']],grammar:'副詞＋正式敬語動詞。하다 語幹在正式語尾中形成 합니다，因此 감사하다 → 감사합니다。'}
];
const review=[vocab[0],vocab[1],vocab[4],vocab[5],vocab[7]];
const choices=['公司','會議','資料','準備','確認','傳送／寄送','今天','明天','先','謝謝'];
const makeChoices=(correct,i)=>[correct,choices[(i+3)%choices.length],choices[(i+6)%choices.length]].sort(()=>Math.random()-.5);
const sets={
'今日新字':vocab.map(v=>({type:'learn',v})),
'單字複習':review.map(v=>({type:'learn',v})),
'看字選意思':vocab.slice(0,5).map((v,i)=>{const a=makeChoices(v.zh,i);return{type:'quiz',t:`<strong style="font-size:1.4rem">${v.ko}</strong> ${audio(v.ko)}<br>這個單字是什麼意思？`,a,c:a.indexOf(v.zh),e:`${v.ko}＝${v.zh}。${v.ex}＝${v.exZh}`,key:v.ko}}),
'聽音選意思':vocab.slice(5,10).map((v,i)=>{const a=makeChoices(v.zh,i+5);return{type:'quiz',t:`先按發音，再選中文意思。<br><br>${audio(v.ko)}`,a,c:a.indexOf(v.zh),e:`你聽到的是「${v.ko}」，意思是「${v.zh}」。`,key:v.ko}}),
'句子拼圖':[
{type:'quiz',t:'請選出「我去公司」的正確排列。',a:['저는 회사에 가요.','회사에 저는 가요.','가요 저는 회사에.'],c:0,e:'韓文常見順序是：主詞＋地點＋動詞。'},
{type:'quiz',t:'請選出「我確認資料」的正確排列。',a:['자료를 저는 확인해요.','저는 자료를 확인해요.','확인해요 자료를 저는.'],c:1,e:'動詞通常放在句子的最後。'}]
};
let active=[],index=0,mode='',answered=false;
const dailyNames=['今日新字','單字複習','看字選意思','聽音選意思','句子拼圖'];
const today=()=>new Date().toLocaleDateString('sv-SE');
const getDaily=()=>{const s=JSON.parse(localStorage.getItem('kkTopikDaily')||'{}');return s.date===today()?s:{date:today(),completed:[]}};
const getWrong=()=>JSON.parse(localStorage.getItem('kkTopikWrongBeginner')||'{}');
const saveWrong=w=>localStorage.setItem('kkTopikWrongBeginner',JSON.stringify(w));
const learnedWordsKey='kkTopikLearnedWords',vocabGoal=200;
const getLearnedWords=()=>JSON.parse(localStorage.getItem(learnedWordsKey)||'[]');
function saveLearnedWord(word){const learned=getLearnedWords();if(!learned.includes(word)){learned.push(word);localStorage.setItem(learnedWordsKey,JSON.stringify(learned))}updateVocabProgress()}
function migrateCompletedVocabulary(){const d=getDaily(),learned=getLearnedWords();if(d.completed.includes('今日新字')&&learned.length===0)localStorage.setItem(learnedWordsKey,JSON.stringify(vocab.map(v=>v.ko)))}
function updateVocabProgress(){const count=getLearnedWords().length,percent=Math.min(100,count/vocabGoal*100),text=document.getElementById('vocabProgressText'),fill=document.getElementById('vocabProgressFill'),bar=document.getElementById('vocabProgressBar'),note=document.getElementById('vocabMilestone');if(text)text.textContent=`已學 ${count} / ${vocabGoal} 字`;if(fill)fill.style.width=`${percent}%`;if(bar)bar.setAttribute('aria-valuenow',String(count));if(note){if(count>=vocabGoal)note.textContent='第一階段完成！你已累積 200 個基礎單字。';else if(count>=100)note.textContent=`已超過一半，距離第一階段還有 ${vocabGoal-count} 字。`;else if(count>=50)note.textContent=`穩定累積中，距離第一階段還有 ${vocabGoal-count} 字。`;else note.textContent=`第一階段目標：200 個基礎單字，還差 ${vocabGoal-count} 字。`}}
function speak(text){if(!('speechSynthesis'in window)){alert('此瀏覽器不支援語音播放。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=.78;speechSynthesis.speak(u)}
function start(name){mode=name;active=name==='錯字再練'?buildWrong():sets[name];index=0;answered=false;const s=document.getElementById('session');s.classList.add('open');document.getElementById('sessionTitle').textContent=name;document.getElementById('sessionHint').textContent=name==='錯字再練'?'答對三次後會從錯字清單移除。':'慢慢看、可以重複播放，不用急。';s.scrollIntoView({behavior:'smooth',block:'start'});render()}
function buildWrong(){return Object.values(getWrong()).map(x=>x.q)}
function render(){const item=active[index];if(!item){finish();return}answered=false;document.getElementById('counter').textContent=`${index+1} / ${active.length}`;document.getElementById('bar').style.width=`${index/active.length*100}%`;document.getElementById('result').textContent='';document.getElementById('explanation').classList.remove('show');document.getElementById('nextRow').innerHTML='';if(item.type==='learn'){const v=item.v;document.getElementById('question').innerHTML=`<article class="word-learning-card"><div class="word-learning-title"><strong>${v.ko}</strong>${audio(v.ko)}</div><div class="word-meaning"><b>中文：</b>${v.zh}　<span>詞性：${v.pos}</span></div><div class="grammar-section"><b>單字解釋</b><p>${v.note}</p></div><div class="grammar-section"><b>例句</b><p><strong>${v.ex}</strong> ${audio(v.ex)}<br>${v.exZh}</p></div><div class="grammar-section"><b>例句拆解</b><ul>${v.parts.map(([ko,zh])=>`<li><strong>${ko}</strong>：${zh}</li>`).join('')}</ul></div><div class="grammar-section usage"><b>文法結構</b><p>${v.grammar}</p></div></article>`;document.getElementById('answers').innerHTML='';document.getElementById('nextRow').innerHTML='<button onclick="next()">我記住了，下一個</button>';return}document.getElementById('question').innerHTML=item.t;document.getElementById('answers').innerHTML=item.a.map((v,i)=>`<button onclick="answer(${i})">${v}</button>`).join('')}
function answer(choice){if(answered)return;answered=true;const item=active[index],ok=choice===item.c,buttons=[...document.querySelectorAll('#answers button')];buttons.forEach((b,i)=>{b.disabled=true;if(i===item.c)b.classList.add('correct');if(i===choice&&!ok)b.classList.add('wrong')});recordWrong(item,ok);document.getElementById('result').textContent=ok?'答對了。':'沒關係，再看一次正確答案。';const ex=document.getElementById('explanation');ex.innerHTML='<strong>說明：</strong>'+item.e;ex.classList.add('show');document.getElementById('nextRow').innerHTML='<button onclick="next()">下一題</button>';updateCounts()}
function recordWrong(item,ok){if(!item.key)return;const w=getWrong();if(!ok)w[item.key]={q:item,right:0};else if(w[item.key]){w[item.key].right++;if(w[item.key].right>=3)delete w[item.key]}saveWrong(w)}
function next(){const item=active[index];if(item?.type==='learn')saveLearnedWord(item.v.ko);index++;render()}
const challengeStorageKey='kkTopikChallengeDays',challengeStart=new Date(2026,6,26);
const getChallengeDates=()=>JSON.parse(localStorage.getItem(challengeStorageKey)||'[]');
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function markTodayChallengeComplete(){const dates=getChallengeDates(),key=today();if(!dates.includes(key)){dates.push(key);localStorage.setItem(challengeStorageKey,JSON.stringify(dates))}}
function finish(){if(dailyNames.includes(mode)){const d=getDaily();if(!d.completed.includes(mode)){d.completed.push(mode);localStorage.setItem('kkTopikDaily',JSON.stringify(d))}if(dailyNames.every(name=>d.completed.includes(name)))markTodayChallengeComplete()}document.getElementById('bar').style.width='100%';document.getElementById('counter').textContent=`${active.length} / ${active.length}`;document.getElementById('question').innerHTML='<div class="finish"><strong>本關完成！</strong><br>今天只要穩定記住幾個字，就是很好的進步。</div>';document.getElementById('answers').innerHTML='';document.getElementById('result').textContent='';document.getElementById('explanation').classList.remove('show');document.getElementById('nextRow').innerHTML='<button onclick="document.getElementById(\'session\').classList.remove(\'open\')">回到關卡列表</button>';updateCounts();renderChallengeCalendar()}
function updateCounts(){const d=getDaily();dailyNames.forEach(n=>document.getElementById('card-'+n)?.classList.toggle('complete',d.completed.includes(n)));document.getElementById('todayProgress').textContent=`今日完成 ${d.completed.length} / ${dailyNames.length} 項`;document.getElementById('wrongCount').textContent=`目前 ${Object.keys(getWrong()).length} 題`;updateVocabProgress()}
let calendarView=new Date();calendarView=new Date(calendarView.getFullYear(),calendarView.getMonth(),1);
function renderChallengeCalendar(){const y=calendarView.getFullYear(),m=calendarView.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),dates=getChallengeDates();document.getElementById('calendarMonth').textContent=`${y} 年 ${m+1} 月`;document.getElementById('calendarStatus').textContent='完成 5 個核心關卡後自動打勾';let h='<div class="calendar-weekdays"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class="calendar-days">'+'<span></span>'.repeat(first);for(let day=1;day<=count;day++){const d=new Date(y,m,day),key=dateKey(d),available=d>=challengeStart,done=dates.includes(key);h+=available?`<div class="calendar-day${done?' challenge':''}" aria-label="${key}${done?' 已完成':' 尚未完成'}">${day}<span class="check${done?'':' empty'}">${done?'✓':''}</span></div>`:`<div class="calendar-day">${day}</div>`}document.getElementById('dynamicCalendar').innerHTML=h+'</div>'}
document.getElementById('previousMonth').onclick=()=>{calendarView.setMonth(calendarView.getMonth()-1);renderChallengeCalendar()};document.getElementById('nextMonth').onclick=()=>{calendarView.setMonth(calendarView.getMonth()+1);renderChallengeCalendar()};
const topics=[
{topic:'工作確認',intro:'今天練習確認工作與禮貌請託。',lines:[{ko:'업무를 확인했습니다.',zh:'我已確認工作內容。',parts:[['업무','工作、業務'],['를','受詞助詞，表示「工作」是確認的對象'],['확인했습니다','확인하다（確認）＋았습니다／었습니다（正式敬語過去式）']],grammar:'名詞＋를／을＋動詞。這句省略主詞「我」，韓文職場對話中很自然。확인했습니다 表示動作已完成，語氣正式、適合向總經理回報。',use:'用於已查看任務、文件或指示後的正式回覆。'},{ko:'잘 부탁드립니다.',zh:'請多多指教／麻煩您了。',parts:[['잘','好好地、順利地'],['부탁','拜託、請託'],['드립니다','드리다（敬語：給、呈上）＋正式語尾ㅂ니다']],grammar:'부탁드리다 是「拜託、請託」的謙讓敬語。整句依情境翻成「請多指教」或「麻煩您了」。',use:'開始合作、提出請求或結束正式訊息時使用。'}]},
{topic:'進度報告',intro:'今天練習簡短而正式地回報進度。',lines:[{ko:'진행 중입니다.',zh:'目前正在進行中。',parts:[['진행','進行、推進'],['중','中、正在某個狀態'],['입니다','이다（是）的正式敬語語尾']],grammar:'名詞＋중이다 表示「正在……中」。主詞與專案名稱常因上下文清楚而省略。',use:'回覆目前工作或專案尚在處理時使用。'},{ko:'곧 공유드리겠습니다.',zh:'我稍後會與您分享。',parts:[['곧','很快、稍後'],['공유','分享'],['드리겠습니다','드리다（謙讓敬語）＋겠습니다（正式未來意志）']],grammar:'공유드리다 是向上級分享的謙讓表達；-겠습니다 表示正式承諾。',use:'準備稍後傳送資料、報告或連結時使用。'}]},
{topic:'會議安排',intro:'今天練習確認會議與正式道別。',lines:[{ko:'회의를 확인했습니다.',zh:'我已確認會議安排。',parts:[['회의','會議'],['를','受詞助詞'],['확인했습니다','已確認；正式敬語過去式']],grammar:'회의＋를＋확인했습니다，結構是「受詞＋動詞」。',use:'收到會議通知、時間或地點後的正式確認。'},{ko:'내일 뵙겠습니다.',zh:'明天見。',parts:[['내일','明天'],['뵙겠습니다','뵙다（見面的謙讓語）＋겠습니다（正式意志）']],grammar:'뵙다 用於見上級或長輩，比 만나요、볼게요 更正式。',use:'預計隔天與總經理見面或開會時使用。'}]}
];
function renderManager(){const t=topics[(new Date().getDate()-1)%topics.length];document.getElementById('dailyTopic').textContent='今日主題：'+t.topic;document.getElementById('dailyManagerIntro').textContent=t.intro;document.getElementById('dailyPhraseList').innerHTML=t.lines.map(line=>`<article class="phrase grammar-card"><div class="manager-sentence"><strong>${line.ko}</strong>${audio(line.ko)}</div><div class="sentence-zh"><b>中文：</b>${line.zh}</div><div class="grammar-section"><b>單字拆解</b><ul>${line.parts.map(([ko,zh])=>`<li><strong>${ko}</strong>：${zh}</li>`).join('')}</ul></div><div class="grammar-section"><b>文法結構</b><p>${line.grammar}</p></div><div class="grammar-section usage"><b>使用情境</b><p>${line.use}</p></div></article>`).join('');document.getElementById('dailyMessageDraft').value=t.lines.map(x=>x.ko).join('\n')}
async function copyDailyDraft(){const d=document.getElementById('dailyMessageDraft');try{await navigator.clipboard.writeText(d.value);document.getElementById('dailyCopyNotice').textContent='已複製，可直接貼到訊息中。'}catch{d.select();document.execCommand('copy')}}
migrateCompletedVocabulary();renderChallengeCalendar();renderManager();updateCounts();